version: '2'
volumes:
  db.mjd-couchdb.data:
    driver: rancher-nfs
    external: true
services:
  db:
    image: registry.spin.nersc.gov/varnerrl/mjd-couchdb:v1.0
    cap_drop:
    - ALL
    cap_add:
    - SETUID
    - SETGID
    - FOWNER
    - CHOWN
    - DAC_OVERRIDE
    volumes:
    - db.mjd-couchdb.data:/opt/couchdb/data
