version: '2'
services:
  app:
    image: my-first-container-app
  web:
    image: my-first-container-nginx
    ports:
    - "81:8080"
    volumes:
    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
